# image:
#   file: .gitpod.Dockerfile

# multi-repo
# additionalRepositories:
#   - url: https://github.com/<redacted>/something
#     checkoutLocation: something

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: |
      # this will install all AWS tools and then open a browser window to authenticate your AWS session
      bash $GITPOD_REPO_ROOT/aws_init.sh
      # put things you want to do with AWS after this line

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview